# Generated by Django 5.0.1 on 2024-03-08 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import got.models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(choices=[('a', 'Motonave'), ('b', 'Buceo'), ('o', 'Oceanografía'), ('l', 'Locativo'), ('v', 'Vehiculos'), ('x', 'Apoyo')], default='a', max_length=1)),
                ('bandera', models.CharField(blank=True, default='Colombia', max_length=50, null=True)),
                ('eslora', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('manga', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('puntal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('calado_maximo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('deadweight', models.IntegerField(blank=True, default=0, null=True)),
                ('arqueo_bruto', models.IntegerField(blank=True, default=0, null=True)),
                ('arqueo_neto', models.IntegerField(blank=True, default=0, null=True)),
                ('espacio_libre_cubierta', models.IntegerField(blank=True, default=0, null=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['area', 'name'],
                'permissions': (('can_see_completely', 'Access to completely info'),),
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.IntegerField()),
                ('location', models.CharField(blank=True, default='Cartagena', max_length=50, null=True)),
                ('state', models.CharField(choices=[('m', 'Mantenimiento'), ('o', 'Operativo'), ('x', 'Fuera de servicio')], default='m', max_length=1)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.asset')),
            ],
            options={
                'ordering': ['asset__name', 'gruop'],
            },
        ),
        migrations.CreateModel(
            name='Ot',
            fields=[
                ('creation_date', models.DateField(auto_now=True)),
                ('num_ot', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('a', 'Abierto'), ('x', 'En ejecucion'), ('f', 'Finalizado'), ('c', 'Cancelado')], default='x', max_length=50)),
                ('tipo_mtto', models.CharField(choices=[('p', 'Preventivo'), ('c', 'Correctivo'), ('m', 'Modificativo')], max_length=1)),
                ('super', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.system')),
                ('info_contratista_pdf', models.FileField(upload_to=got.models.get_upload_path, null=True, blank=True)),
            ],
            options={
                'ordering': ['-num_ot'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('date_inv', models.DateField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('feature', models.TextField()),
                ('prom_hours', models.IntegerField(blank=True, default=0, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='got.system')),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('hse', models.TextField(blank=True, default='', null=True)),
                ('procedimiento', models.TextField(blank=True, default='', null=True)),
                ('suministros', models.TextField(blank=True, default='', null=True)),
                ('news', models.TextField(blank=True, null=True)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('men_time', models.IntegerField(default=0)),
                ('finished', models.BooleanField()),
                ('ot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.ot')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
