# Generated by Django 5.0.1 on 2024-03-06 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ot',
            options={'ordering': ['num_ot']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.AddField(
            model_name='asset',
            name='area',
            field=models.CharField(choices=[('b', 'Buceo'), ('a', 'Artefactos Navales'), ('o', 'Oceanografia'), ('l', 'Locativo'), ('v', 'Vehiculos')], default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.CharField(choices=[('m', 'Mantenimiento'), ('o', 'Operacion'), ('d', 'Dique'), ('x', 'Fuera de servicio')], default='m', max_length=50),
        ),
        migrations.AlterField(
            model_name='ot',
            name='state',
            field=models.CharField(choices=[('a', 'Abierto'), ('x', 'En ejecucion'), ('f', 'Finalizado'), ('c', 'Cancelado')], default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='men_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='ot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.ot'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),

        migrations.AlterField(
            model_name='task',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.ruta'),
        ),
    ]
