# Generated by Django 5.0.1 on 2024-03-03 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.CharField(choices=[('m', 'Mantenimiento'), ('o', 'Operacion'), ('d', 'Dique'), ('x', 'Fuera de servicio')], default='m', max_length=50),
        ),
        migrations.AlterField(
            model_name='ot',
            name='state',
            field=models.CharField(choices=[('a', 'Abierto'), ('x', 'En ejecucion'), ('f', 'Finalizado'), ('c', 'Cancelado')], default='a', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('date_inv', models.DateField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location_int', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('feature', models.TextField()),
                ('state', models.CharField(choices=[('m', 'Mantenimiento'), ('o', 'Operativo'), ('x', 'Fuera de servicio')], max_length=50)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='got.system')),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('frecuency', models.IntegerField()),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('intervention_date', models.DateField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='got.equipo')),
            ],
        ),
    ]
