# Generated by Django 5.0.1 on 2024-02-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['asset__name', 'gruop']},
        ),
    ]
