# Generated by Django 5.0.1 on 2024-03-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0002_alter_ot_options_remove_asset_location_asset_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='location_int',
            new_name='location',
        ),
    ]
