# Generated by Django 5.0.1 on 2024-03-08 04:01

import django.db.models.deletion
import got.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0002_ruta_task_ruta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historyhour',
            unique_together={('component', 'report_date')},
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=got.models.get_upload_pdfs)),
                ('description', models.CharField(max_length=200)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='got.asset')),
                ('tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='got.task')),
            ],
        ),

        migrations.CreateModel(
            name='Megger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.ot')),
            ],
        ),
        migrations.CreateModel(
            name='Excitatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_1min_l_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_10min_l_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_obs_l_tierra', models.TextField(blank=True, null=True)),
                ('pf_1min_l_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_10min_l_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_obs_l_tierra', models.TextField(blank=True, null=True)),
                ('megger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.megger')),
            ],
        ),
        migrations.CreateModel(
            name='Estator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_1min_l1_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_1min_l2_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_1min_l3_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_1min_l1_l2', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_1min_l2_l3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_1min_l3_l1', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_10min_l1_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_10min_l2_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_10min_l3_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_10min_l1_l2', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_10min_l2_l3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_10min_l3_l1', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pi_obs_l1_tierra', models.TextField(blank=True, null=True)),
                ('pi_obs_l2_tierra', models.TextField(blank=True, null=True)),
                ('pi_obs_l3_tierra', models.TextField(blank=True, null=True)),
                ('pi_obs_l1_l2', models.TextField(blank=True, null=True)),
                ('pi_obs_l2_l3', models.TextField(blank=True, null=True)),
                ('pi_obs_l3_l1', models.TextField(blank=True, null=True)),
                ('pf_1min_l1_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_1min_l2_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_1min_l3_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_1min_l1_l2', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_1min_l2_l3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_1min_l3_l1', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_10min_l1_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_10min_l2_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_10min_l3_tierra', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_10min_l1_l2', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_10min_l2_l3', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_10min_l3_l1', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('pf_obs_l1_tierra', models.TextField(blank=True, null=True)),
                ('pf_obs_l2_tierra', models.TextField(blank=True, null=True)),
                ('pf_obs_l3_tierra', models.TextField(blank=True, null=True)),
                ('pf_obs_l1_l2', models.TextField(blank=True, null=True)),
                ('pf_obs_l2_l3', models.TextField(blank=True, null=True)),
                ('pf_obs_l3_l1', models.TextField(blank=True, null=True)),
                ('megger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.megger')),
            ],
        ),
        migrations.CreateModel(
            name='RodamientosEscudos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodamientoas', models.TextField(blank=True, null=True)),
                ('rodamientobs', models.TextField(blank=True, null=True)),
                ('escudoas', models.TextField(blank=True, null=True)),
                ('escudobs', models.TextField(blank=True, null=True)),
                ('megger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.megger')),
            ],
        ),
        migrations.CreateModel(
            name='RotorAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_1min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pi_10min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pi_obs_l_tierra', models.TextField(blank=True, null=True)),
                ('pf_1min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pf_10min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pf_obs_l_tierra', models.TextField(blank=True, null=True)),
                ('megger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.megger')),
            ],
        ),
        migrations.CreateModel(
            name='RotorMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_1min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pi_10min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pi_obs_l_tierra', models.TextField(blank=True, null=True)),
                ('pf_1min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pf_10min_l_tierra', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pf_obs_l_tierra', models.TextField(blank=True, null=True)),
                ('megger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.megger')),
            ],
        ),
    ]
