# Generated by Django 5.0.1 on 2024-03-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0002_alter_asset_state_alter_ot_state_alter_task_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
