# Generated by Django 5.0.1 on 2024-05-27 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_remove_task_ruta_delete_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='state',
            field=models.CharField(choices=[('a', 'Abierto'), ('x', 'En ejecución'), ('f', 'Finalizado'), ('c', 'Cancelado')], default='x', max_length=1),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='got.equipo'),
        ),
    ]
