# Generated by Django 5.0.1 on 2024-06-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_remove_task_ruta_delete_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='seccion',
            field=models.CharField(choices=[('c', 'Consumibles'), ('h', 'Herramientas'), ('r', 'Repuestos')], default='r', max_length=1),
        ),
    ]
