# Generated by Django 5.0.1 on 2024-03-07 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0003_rename_location_int_equipo_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtefactoNaval',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='got.asset')),
                ('bandera', models.CharField(default='Colombia', max_length=50)),
                ('eslora', models.IntegerField(default=0)),
                ('manga', models.IntegerField(default=0)),
                ('puntal', models.IntegerField(default=0)),
                ('calado_maximo', models.IntegerField(default=0)),
                ('deadweight', models.IntegerField(default=0)),
                ('arqueo_bruto', models.IntegerField(default=0)),
                ('arqueo_neto', models.IntegerField(default=0)),
                ('espacio_libre_cubierta', models.IntegerField(default=0)),
            ],
            bases=('got.asset',),
        ),
        migrations.RemoveField(
            model_name='asset',
            name='state',
        ),
        migrations.AddField(
            model_name='ot',
            name='tipo_mtto',
            field=models.CharField(choices=[('p', 'Preventivo'), ('c', 'Correctivo'), ('m', 'Modificativo')], default='c', max_length=50),
        ),
    ]
