# Generated by Django 5.0.1 on 2024-06-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_alter_equipo_volumen_alter_solicitud_seccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='megger',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('r', 'Rotativo'), ('nr', 'No rotativo'), ('e', 'Motor eléctrico')], default='nr', max_length=2),
        ),
    ]
