# Generated by Django 5.0.1 on 2024-05-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_ruta_task_ruta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', '-start_date'], 'permissions': (('can_reschedule_task', 'Reprogramar actividades'),)},
        ),
    ]
