# Generated by Django 5.0.1 on 2024-03-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_ruta_task_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='got.system'),
        ),
    ]
