# Generated by Django 5.0.1 on 2024-02-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_component_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='component',
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('date_inv', models.DateField(blank=True, null=True)),
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location_int', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('serial', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=50, null=True)),
                ('feature', models.TextField()),
                ('state', models.CharField(choices=[('m', 'Mantenimiento'), ('o', 'Operativo'), ('x', 'Fuera de servicio')])),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='got.system')),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Rut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('frecuency', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.equipo')),
            ],
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
    ]
