# Generated by Django 5.0.1 on 2024-03-07 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0004_artefactonaval_remove_asset_state_ot_tipo_mtto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtefactoNaval',
        ),
    ]
