# Generated by Django 5.0.1 on 2024-05-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_alter_ruta_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='astillero',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalFailureReport',
        ),
    ]
