# Generated by Django 5.0.1 on 2024-05-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_alter_ruta_astillero_megger_delete_salidaitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Megger',
        ),
    ]
