# Generated by Django 5.0.1 on 2024-05-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_alter_ruta_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalot',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalot',
            name='super',
        ),
        migrations.RemoveField(
            model_name='historicalot',
            name='system',
        ),
        migrations.RemoveField(
            model_name='historicalruta',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='historicalruta',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='historicalruta',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalruta',
            name='ot',
        ),
        migrations.RemoveField(
            model_name='historicalruta',
            name='system',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='ot',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='ruta',
        ),
        migrations.AddField(
            model_name='ruta',
            name='astillero',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalFailureReport',
        ),
        migrations.DeleteModel(
            name='HistoricalOt',
        ),
        migrations.DeleteModel(
            name='HistoricalRuta',
        ),
        migrations.DeleteModel(
            name='HistoricalTask',
        ),
    ]
