# Generated by Django 5.0.1 on 2024-04-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_alter_ruta_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='suministros',
        ),
        migrations.RemoveField(
            model_name='task',
            name='suministros',
        ),
        migrations.AddField(
            model_name='historicalot',
            name='suministros',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='historicalruta',
            name='suministros',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='ot',
            name='suministros',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='suministros',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
