# Generated by Django 5.0.1 on 2024-03-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0005_delete_artefactonaval'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='arqueo_bruto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='arqueo_neto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='bandera',
            field=models.CharField(blank=True, default='Colombia', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='calado_maximo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='deadweight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='eslora',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='espacio_libre_cubierta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='manga',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='puntal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
