# Generated by Django 5.0.1 on 2024-05-14 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0006_remove_historicalot_history_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historyhour',
            unique_together={('component', 'report_date')},
        ),
    ]
