# Generated by Django 5.0.1 on 2024-05-16 03:16

import django.contrib.postgres.fields
import got.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0006_remove_historicalot_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=got.models.get_upload_path), blank=True, null=True, size=10),
        ),
    ]
