# Generated by Django 5.0.1 on 2024-06-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0006_alter_estator_megger_alter_excitatriz_megger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ot',
            name='suministros',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='suministros',
        ),
        migrations.AddField(
            model_name='equipo',
            name='potencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='control',
            field=models.CharField(choices=[('d', 'Días'), ('h', 'Horas'), ('k', 'Kilómetros')], max_length=1),
        ),
    ]
