# Generated by Django 5.0.1 on 2024-03-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0006_asset_arqueo_bruto_asset_arqueo_neto_asset_bandera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='calado_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='eslora',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manga',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='puntal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='ot',
            name='state',
            field=models.CharField(choices=[('a', 'Abierto'), ('x', 'En ejecucion'), ('f', 'Finalizado'), ('c', 'Cancelado')], default='x', max_length=50),
        ),
    ]
