# Generated by Django 5.0.1 on 2024-04-21 13:11

import got.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0006_equipo_manual_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path),
        ),
    ]
