# Generated by Django 5.0.1 on 2024-06-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0006_alter_estator_megger_alter_excitatriz_megger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministro',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.equipo'),
        ),
        migrations.AlterField(
            model_name='suministro',
            name='Solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='got.solicitud'),
        ),
    ]
