# Generated by Django 5.0.1 on 2024-05-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0007_location_asset_abbreviation_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='lubricante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='volumen',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
