# Generated by Django 5.0.1 on 2024-06-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0007_suministro_equipo_alter_suministro_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suministros', to='got.equipo'),
        ),
        migrations.AlterField(
            model_name='system',
            name='state',
            field=models.CharField(choices=[('m', 'Mantenimiento'), ('o', 'Operativo'), ('x', 'Fuera de servicio'), ('s', 'Stand by')], default='m', max_length=1),
        ),
    ]
