# Generated by Django 5.0.1 on 2024-03-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0007_ruta_name_alter_ruta_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ot',
            options={'ordering': ['-num_ot']},
        ),
        migrations.AddField(
            model_name='ot',
            name='info_contratista_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
