# Generated by Django 5.0.1 on 2024-05-06 02:49

import django.db.models.deletion
import got.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0007_location_asset_abbreviation_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='got.equipo'),
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('persona_transporte', models.CharField(max_length=100)),
                ('matricula_vehiculo', models.CharField(max_length=10)),
                ('lugar_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.location')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.component')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='got.salida')),
            ],
        ),
    ]
