# Generated by Django 5.0.1 on 2024-05-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0008_alter_megger_estator_pf_10min_l1_l2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', '-start_date'], 'permissions': (('can_reschedule_task', 'Reprogramar actividades'), ('can_modify_any_task', 'Can modify any task'))},
        ),
    ]
