# Generated by Django 5.0.1 on 2024-05-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0008_alter_component_equipo_salida_salidaitem'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='asset',
        #     name='id',
        # ),
        # migrations.AlterField(
        #     model_name='asset',
        #     name='abbreviation',
        #     field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        # ),
    ]
