# Generated by Django 5.0.1 on 2024-03-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0008_remove_equipo_area_equipo_horometro_equipo_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='initial_hours',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ruta',
            name='control',
            field=models.CharField(choices=[('d', 'Días'), ('h', 'Horas')], max_length=1),
        ),
    ]
