# Generated by Django 5.0.1 on 2024-04-06 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0008_remove_equipo_area_equipo_horometro_equipo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['frecuency']},
        ),
        migrations.AddField(
            model_name='ruta',
            name='dependencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependiente', to='got.ruta'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='initial_hours',
            field=models.IntegerField(default=0),
        ),
    ]
