# Generated by Django 5.0.1 on 2024-03-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0008_alter_ot_options_ot_info_contratista_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
