# Generated by Django 5.0.1 on 2024-03-08 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0008_remove_equipo_location_remove_equipo_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='got.system'),
        ),
    ]
