# Generated by Django 5.0.1 on 2024-03-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0009_alter_ot_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
