# Generated by Django 5.0.1 on 2024-03-08 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0009_alter_equipo_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['area', 'name'], 'permissions': (('can_see_completely', 'Access to completely info'),)},
        ),
    ]
