# Generated by Django 5.0.1 on 2024-03-27 14:42

import django.db.models.deletion
import got.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0010_alter_equipo_initial_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='manual_pdf',
            field=models.FileField(blank=True, null=True, upload_to=got.models.get_upload_pdfs),
        ),
        migrations.AlterField(
            model_name='failurereport',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='failurereport',
            name='related_ot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_report', to='got.ot'),
        ),
        migrations.AlterField(
            model_name='ot',
            name='info_contratista_pdf',
            field=models.FileField(blank=True, null=True, upload_to=got.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='task',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path),
        ),
    ]
