# Generated by Django 5.0.1 on 2024-06-07 02:52

import django.db.models.deletion
import got.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0010_document_tasks_megger_excitatriz_estator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=got.models.get_upload_path)),
                ('presentacion', models.CharField(max_length=10)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('seccion', models.CharField(choices=[('c', 'Consumibles'), ('h', 'Herramientas'), ('r', 'Repuestos')], default='c', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='image',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='got.solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('Solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.solicitud')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='got.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
    ]
