# Generated by Django 5.0.1 on 2024-03-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0011_task_hse_task_procedimiento_task_suministros'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='prom_hours',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
