# Generated by Django 5.0.1 on 2024-03-27 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0011_task_hse_task_procedimiento_task_suministros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failurereport',
            options={'ordering': ['-moment']},
        ),
        migrations.AlterModelOptions(
            name='historyhour',
            options={'ordering': ['-report_date']},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['asset__name', 'group']},
        ),
        migrations.AddField(
            model_name='failurereport',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='failurereport',
            name='related_ot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_report', to='got.ot'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='area',
            field=models.CharField(choices=[('a', 'Motonave'), ('b', 'Buceo'), ('o', 'Oceanografía'), ('l', 'Locativo'), ('v', 'Vehiculos'), ('x', 'Apoyo')], default='a', max_length=1),
        ),
    ]
