# Generated by Django 5.0.1 on 2024-04-04 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0011_rename_finished_failurereport_closed_ruta_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyhour',
            name='hour',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
