# Generated by Django 5.0.1 on 2024-06-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0011_alter_solicitud_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='num_sc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
