# Generated by Django 5.0.1 on 2024-03-17 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('got', '0012_equipo_prom_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='got.equipo'),
        ),
    ]
