# Generated by Django 5.0.1 on 2024-06-06 18:26

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('got', '0012_solicitud_num_sc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
